services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # Use cases
  IsEazy\WinesMesasurements\Application\:
    resource: '../../src/Application/*/*/Validator/{*CommandValidator.php,*QueryValidator.php}'
    tags:
      - { name: iseazy.cqrs.command_validator }