parameters:
    translator_allowed_locales:
        - 'en_UK'
        - 'es_ES'

services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    # sample event listener
    #IsEazy\WinesMesasurements\Infrastructure\Shared\Symfony\EventListener\TranslatorRequestListener:
    #    class: ~
    #    public: true
    #    arguments: ['%translator_allowed_locales%']
    #    tags:
    #       - { name: kernel.event_listener, event: kernel.request }

