doctrine:
    dbal:
        charset: 'utf8mb4'
        driver: 'pdo_mysql'
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
        types:
            #uuid: IsEazy\Doctrine\Dbal\Types\UuidType


        mapping_types:
            uuid: binary
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true

        # Doctrine Extensions Filters
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true

        mappings:
            #Example:
            #    is_bundle: false
            #    type: xml
            #    dir: '%kernel.project_dir%/config/doctrine/persistence/Example/Model'
            #    prefix: 'IsEazy\WinesMesasurements\Domain\Example\Model'
            #    alias: Example