FROM iseazytech/slate:2.10.0-dev

RUN cp /srv/slate/source/stylesheets/_variables.scss /srv/slate/source/stylesheets/_variables.scss.original
RUN cp /srv/slate/source/stylesheets/screen.css.scss /srv/slate/source/stylesheets/screen.css.scss.original
RUN cp /srv/slate/config.rb /srv/slate/config.rb.original